[workspace]
members = ["codegen", "."]

[package]
name = "dynec"
authors = ["SOFe <sofe2038@gmail.com>"]
version = "0.2.0"
edition = "2021"
repository = "https://github.com/SOF3/dynec"
homepage = "https://github.com/SOF3/dynec"
description = "An opinionated ECS-like framework"
license = "Apache-2.0"

[dependencies]
bitvec = "1.0.0"
dynec-codegen = {version = "0.2.0", path = "codegen"}
itertools = "0.10.3"
num-traits = "0.2.14"
xias = "0.2.1"
