on: [pull_request]
name: benchmark
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: boa-dev/criterion-compare-action@v3
        with:
          features: "internal-bench"
          token: ${{ github.token }}
          branchName: ${{ github.base_ref }}
