name: Docs build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: "Documentation build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-27
          profile: default
          default: true

      - name: Install mdbook
        run: wget -O - https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar xz

      - name: Build documentation without private items
        run: cargo doc && mv target/doc ..staging
      - name: Build documentation with private items
        run: cargo doc --document-private-items --all --all-features && mv target/doc ..staging/private

      - name: Build book
        run: ./mdbook build -d $PWD/..staging/book book

      - name: Clone site repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{secrets.API_KEY}}
          path: ..site-repo
          ref: gh-pages
      - name: Delete previous build
        run: test ! -d $(echo ${{github.ref}} | cut -d/ -f3) || rm -r $(echo ${{github.ref}} | cut -d/ -f3)
        working-directory: ..site-repo

      - name: Copy artifact to site repo
        run: cp -r ..staging ..site-repo/$(echo ${{github.ref}} | cut -d/ -f3)

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Git commit
        run: git add $(echo ${{github.ref}} | cut -d/ -f3) && git commit --allow-empty -m "Docs build for SOF3/dynec@${{github.sha}}"
        working-directory: ..site-repo

      - name: Push pages
        run: git push
        working-directory: ..site-repo
